# Specify the file containing the instructions OR
# give them in the message.
# Currently the poses are noise free.

string filename
string[] instructions
bool reload_scene
bool start_scene
---
bool result
